/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.97.2
*/

import { ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions } from "fuels";

import { DieselAmmContract } from './DieselAmmContract.js';

const bytecode = decompressBytecode("");

export class DieselAmmContractFactory extends ContractFactory<DieselAmmContract> {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(
      bytecode,
      DieselAmmContract.abi,
      accountOrProvider,
      DieselAmmContract.storageSlots
    );
  }

  static deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ) {
    const factory = new DieselAmmContractFactory(wallet);
    return factory.deploy(options);
  }
}
