/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.97.2
*/

export { DieselAmmContract } from './DieselAmmContract.js';
export { DieselAmmContractFactory } from './DieselAmmContractFactory.js';
